# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_builder_pb2 as image__builder__pb2


class ImageBuilderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Build = channel.unary_stream(
                '/ImageBuilder/Build',
                request_serializer=image__builder__pb2.BuildRequest.SerializeToString,
                response_deserializer=image__builder__pb2.BuildLog.FromString,
                )
        self.Query = channel.unary_unary(
                '/ImageBuilder/Query',
                request_serializer=image__builder__pb2.BuildQuery.SerializeToString,
                response_deserializer=image__builder__pb2.BuildResponse.FromString,
                )


class ImageBuilderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Build(self, request, context):
        """Simple RPC service for building images
        rpc Build(BuildRequest) returns (BuildResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageBuilderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Build': grpc.unary_stream_rpc_method_handler(
                    servicer.Build,
                    request_deserializer=image__builder__pb2.BuildRequest.FromString,
                    response_serializer=image__builder__pb2.BuildLog.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=image__builder__pb2.BuildQuery.FromString,
                    response_serializer=image__builder__pb2.BuildResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageBuilder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageBuilder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Build(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ImageBuilder/Build',
            image__builder__pb2.BuildRequest.SerializeToString,
            image__builder__pb2.BuildLog.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageBuilder/Query',
            image__builder__pb2.BuildQuery.SerializeToString,
            image__builder__pb2.BuildResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
