name: m1l0-image-builder_pull
on: pull_request
jobs:
  build:
    name: "Running tests and linting"
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run test
        run: |
          python setup.py test 
      - name: Run flake8
        run: |
          python setup.py flake8