name: m1l0-image-builder_push
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  run_tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run test
        run: |
          python setup.py test

  deploy:
    name: "Deploy to Dockerhub"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata tags labels for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: m1l0/imagebuilder
          flavor: |
            latest=true

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != "pull_request" }}
          tags: ${{ steps.meta.output.tags }}
          labels: ${{ steps.meta.outputs.labels }}

